### PR TITLE
Fix packages

### PR DESCRIPTION
**Pull request by szepeviktor**
@adamlaki 

#55

### CODE REVIEW

**Comment by szepeviktor** [comment]
:x: stylelint has some output

**Comment by adamlaki** [comment]
Thanks Viktor! 

I try to crack why the heck it won't instal those at my local environment...

**Comment by adamlaki** [comment]
I don't know what it is; no matter how I install it locally, it leaves out those three dependencies...

**Comment by adamlaki** [comment]
Thanks for you help!

**Comment by szepeviktor** [comment]
... maybe globally installed packages

**Pull request merged**
