### PR TITLE
Do not store CSS in the repo

### LINKED ISSUE #15: CSS in the repo
Should we remove `main.css`?

### PR DESCRIPTION
**Pull request by szepeviktor**
Closes #15

### CODE REVIEW

**Comment by szepeviktor** [comment]
@adamlaki What npm script does Eleventy runs when deploying?

**Comment by szepeviktor** [comment]
https://docs.netlify.com/configure-builds/file-based-configuration/#build-settings

**Comment by szepeviktor** [comment]
@adamlaki Please consider moving Netlify setting from the UI to `netlify.toml`

**Comment by adamlaki** [comment]
Ohh, you don't say that my problem was the script order? :|

**Comment by szepeviktor** [comment]
I don't know what npm script Netlify run on deploy, maybe `npm run build`.
Please see the deploy log.

**Comment by adamlaki** [comment]
Thank you Viktor!

**Pull request merged**
