### PR TITLE
Run Lychee as an action

### PR DESCRIPTION
**Pull request by szepeviktor**
@adamlaki Here we go! No more broken links.

[_source_](https://github.com/szepeviktor/byte-level-care/blob/361131f10976e889fce51bba5775fd8040d0862b/.github/workflows/markdown.yml#L47-L60)

### CODE REVIEW

**Comment by szepeviktor** [comment]
Please fix the two broken links in https://github.com/conedevelopment/cone-site/pull/43
Thank you!

**Comment by adamlaki** [comment]
Thanks, Viktor! The last version finally ran but this is nicer.

**Comment by szepeviktor** [comment]
> The last version

Installing Lychee as a cargo package takes 3 minutes **every time**.

**Comment by szepeviktor** [comment]
And the action has very nice output: https://github.com/conedevelopment/sprucecss-site-eleventy/actions/runs/8116911167#summary-22187952138

**Comment by adamlaki** [comment]
> Installing Lychee as a cargo package takes 3 minutes every time.

Yeah, that was a main concern. :|

**Comment by adamlaki** [comment]
https://github.com/conedevelopment/sprucecss-site-eleventy/actions/runs/8116962078/job/22188114123 🥳 

Thanks Viktor!

**Comment by szepeviktor** [comment]
Glad to contribute.

image

**Pull request merged**
