### PR TITLE
Build website in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
@adamlaki What is the URL?
Could you add it?

### CODE REVIEW

**Comment by adamlaki** [comment]
@szepeviktor I could add it, but it is a private URL. How can I add it?

**Comment by adamlaki** [comment]
@szepeviktor I mean without exposing it?

**Comment by szepeviktor** [comment]
In a GitHub Environment secret.

But that this makes the whole project private.
A simple githubber won't be able to contribute.

**Comment by adamlaki** [comment]
I think then it would be best to make a dummy endpoint with fewer examples. It is not a concern right now but could be in the future, so I still want the right endpoint hidden.

**Comment by adamlaki** [comment]
I've made a fix to this. Now if there is no URL we give back two fake data.

**Comment by adamlaki** [comment]
Thanks for the PR and for resolving the conflict! ❤️

**Pull request merged**
